### ISSUE TITLE
this should work

### ISSUE THREAD

**Issue by strteamservidores** [nuclearsilo583/zephyrus-store-preview-new-syntax#140]
the arms are not changing.

```
"Store"
{
    "★ Luvas Personalizadas"
    {
        "Karachenko"
        {
            "model" "models/weapons/v_models/arms/karachenko/karachenko.mdl"
            "team" "4"
            "type" "arms"
            "unique_id" "karachenko"
            "Plans"
            {
                "1 Dia"
                {
                    "price" "2500"
                    "time"  "86400"
                }
                "Permanente"
                {
                    "price" "9000"
                }
            }
        }
    }
}
```

**Comment by nuclearsilo583** [comment]
fixed.

**Comment by strteamservidores** [comment]
Thanks but still with some bugs
![de_mirage0009](https://user-images.githubusercontent.com/69168702/217051991-05f5480c-bb7b-4950-8ee3-a95a365ec1c2.png)

**Comment by nuclearsilo583** [comment]
Please take a look at [this](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/issues/50)

**Comment by strteamservidores** [comment]
i tried to install n arms fix extension and plugin, but still not working 😢

**Comment by nuclearsilo583** [comment]
Does the arms fix extension running. type meta list and sm exts list in your server console.

**Comment by strteamservidores** [comment]
Meta List:
```
Listing 9 plugins:
  [01] SourceMod (1.11.0.6928) by AlliedModders LLC
  [02] CSGO-ArmsFix (1.0) by Kyle (4y)
  [03] CS Tools (1.11.0.6928) by AlliedModders LLC
  [04] SDK Tools (1.11.0.6928) by AlliedModders LLC
  [05] SDK Hooks (1.11.0.6928) by AlliedModders LLC
  [06] SteamWorks Extension (1.2.3) by Kyle Sanderson
  [07] PTaH (1.1.3) by Phoenix (˙·٠●Феникс●٠·˙)
  [08] SourceTV Manager (1.2) by Peace-Maker
  [09] DHooks (1.11.0.6928) by AlliedModders LLC
```

sm exts list:
```
[SM] Displaying 23 extensions:
[01] Automatic Updater (1.11.0.6928): Updates SourceMod gamedata files
[02] Webternet (1.11.0.6928): Extension for interacting with URLs
[03] CSGO-ArmsFix (1.0): Fix glove overcap with custom arms
[04] Console Cleaner (1.3.0): Console warning suppressor
[05] cURL Extension (1.3.0.0): cURL Extension
[06] CS Tools (1.11.0.6928): CS extended functionality
[07] BinTools (1.11.0.6928): Low-level C/C++ Calling API
[08] SDK Tools (1.11.0.6928): Source SDK Tools
[09] SDK Hooks (1.11.0.6928): Source SDK Hooks
[10] Client Preferences (1.11.0.6928): Saves client preference settings
[11] SQLite (1.11.0.6928): SQLite Driver
[12] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[13] PTaH (1.1.3): Additional CS:GO Hooks and Natives
[14] REST in Pawn (1.3.1): Provides HTTP and JSON natives for plugins
[15] SourceTV Manager (1.2): Interface to interact with the SourceTV server.
[16] Top Menus (1.11.0.6928): Creates sorted nested menus
[17] Regex (1.11.0.6928): Provides regex natives for plugins
[18] GeoIP (1.11.0.6928): Geographical IP information
[19] DHooks (1.11.0.6928): Dynamic Hooks
[20] SMJansson (2.3.1/3): JSON parser/writer
[21] SMbz2 (0.0.3): Very basic extension to de/compress bz2 files
[22] Socket (3.0.2): Socket extension for SourceMod
[23] MySQL-DBI (1.11.0.6928): MySQL driver implementation for DBI
```

**Comment by strteamservidores** [comment]
Here a video showing: https://streamable.com/8sefdq
